name: Publish Water News

on:
  push:
    branches:
      - main
    paths:
      - 'news/news.json'
  workflow_dispatch: # امکان اجرای دستی از تب Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy news.json to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "news/news.json"
          target: "/var/www/royab-site/"
          strip_components: 1 # باعث می‌شود پوشه news حذف شده و فایل مستقیم داخل royab-site کپی شود
          overwrite: true
