name: Deploy News to Royab Server

on:
  push:
    paths:
      - 'news/*.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy news.json to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 # در صورت متفاوت بودن پورت SSH سرور پارس‌پک، این مقدار را تغییر دهید
          source: "news/news.json"
          target: "/var/www/royab/site/"
          strip_components: 1
